server: 
  port: 8081
  servlet: 
    context-path: /sso-resource-server

####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss}[%X{traceId}/%X{spanId}] [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss}[%X{traceId}/%X{spanId}] [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: sso-resource-server.log